version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "test"
s3_bucket = "samartifactbuckettm"
s3_prefix = "test"
region = "eu-central-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Table=\"Todos\" Region=\"eu-central-1\""
image_repositories = []
resolve_s3 = false
confirm_changeset = true
disable_rollback = true